@echo off

set "DEFAULT_PROJ_ROOT=%~dp0.."

set "SERVICE_PM_NAME=p_m"
set "SERVICE_ITM_NAME=i_t_m"
set "SERVICE_OM_NAME=o_m"
set "SERVICE_CSARM_NAME=c_s_a_r_m"
set "SERVICE_IARM_NAME=i_a_r_m"
set "SERVICE_OIM_NAME=o_i_m"
set "SERVICE_PRM_NAME=pr_m"
set "SERVICE_TAM_NAME=t_a_m"
set "SERVICE_TBM_NAME=t_b_m"
set "SERVICE_TDM_NAME=t_d_m"
set "SERVICE_TEM_NAME=t_e_m"
set "SERVICE_VM_NAME=v_m"
set "SERVICE_WMJ_NAME=w_mj"

set "P_M_SERVER_PORT=6006"
set "I_T_M_SERVER_PORT=6001"
set "O_M_SERVER_PORT=6009"
set "C_S_A_R_M_SERVER_PORT=6013"
set "I_A_R_M_SERVER_PORT=6017"
set "O_I_M_SERVER_PORT=6011"
set "PR_M_SERVER_PORT=6007"
set "T_A_M_SERVER_PORT=6010"
set "T_B_M_SERVER_PORT=6015"
set "T_D_M_SERVER_PORT=6016"
set "T_E_M_SERVER_PORT=6012"
set "V_M_SERVER_PORT=6014"
set "W_MJ_SERVER_PORT=6008"

set "P_M_SERVER_PATH=src\servers\m\g\p_m\basic\app.py"
set "I_T_M_SERVER_PATH=src\servers\m\g\i_t_m\basic\app.py"
set "O_M_SERVER_PATH=src\servers\m\g\o_m\basic\app.py"
set "C_S_A_R_M_SERVER_PATH=src\servers\m\g\c_s_a_r_m\basic\app.py"
set "I_A_R_M_SERVER_PATH=src\servers\m\g\i_a_r_m\basic\app.py"
set "O_I_M_SERVER_PATH=src\servers\m\g\o_i_m\basic\app.py"
set "PR_M_SERVER_PATH=src\servers\m\g\pr_m\basic\app.py"
set "T_A_M_SERVER_PATH=src\servers\m\g\t_a_m\basic\app.py"
set "T_B_M_SERVER_PATH=src\servers\m\g\t_b_m\basic\app.py"
set "T_D_M_SERVER_PATH=src\servers\m\g\t_d_m\basic\app.py"
set "T_E_M_SERVER_PATH=src\servers\m\g\t_e_m\basic\app.py"
set "V_M_SERVER_PATH=src\servers\m\g\v_m\basic\app.py"
set "W_MJ_SERVER_PATH=src\servers\m\g\w_mj\basic\app.py"

